// <auto-generated />
using System;
using CostPlanningServer.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CostPlanningServer.Migrations
{
    [DbContext(typeof(CostPlanningContext))]
    [Migration("20210210122728_SyncVisible")]
    partial class SyncVisible
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CostPlanningServer.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsVisible = false,
                            Name = "Hrana",
                            ServerId = 0
                        },
                        new
                        {
                            Id = 2,
                            IsVisible = false,
                            Name = "Razno",
                            ServerId = 0
                        },
                        new
                        {
                            Id = 3,
                            IsVisible = false,
                            Name = "Putovanja",
                            ServerId = 0
                        });
                });

            modelBuilder.Entity("CostPlanningServer.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CostPlanningServer.Model.SyncVisible<CostPlanningServer.Model.Category>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("SyncVisible<Category>");
                });

            modelBuilder.Entity("CostPlanningServer.Model.SyncVisible<CostPlanningServer.Model.Order>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("SyncVisible<Order>");
                });

            modelBuilder.Entity("CostPlanningServer.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SyncVisible<Category>Id")
                        .HasColumnType("int");

                    b.Property<int?>("SyncVisible<Order>Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SyncVisible<Category>Id");

                    b.HasIndex("SyncVisible<Order>Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CostPlanningServer.Model.Order", b =>
                {
                    b.HasOne("CostPlanningServer.Model.Category", "Category")
                        .WithMany("Orders")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CostPlanningServer.Model.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CostPlanningServer.Model.SyncVisible<CostPlanningServer.Model.Category>", b =>
                {
                    b.HasOne("CostPlanningServer.Model.Category", "Item")
                        .WithOne("SyncVisible")
                        .HasForeignKey("CostPlanningServer.Model.SyncVisible<CostPlanningServer.Model.Category>", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CostPlanningServer.Model.SyncVisible<CostPlanningServer.Model.Order>", b =>
                {
                    b.HasOne("CostPlanningServer.Model.Order", "Item")
                        .WithOne("SyncVisible")
                        .HasForeignKey("CostPlanningServer.Model.SyncVisible<CostPlanningServer.Model.Order>", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CostPlanningServer.Model.User", b =>
                {
                    b.HasOne("CostPlanningServer.Model.SyncVisible<CostPlanningServer.Model.Category>", null)
                        .WithMany("SyncUsers")
                        .HasForeignKey("SyncVisible<Category>Id");

                    b.HasOne("CostPlanningServer.Model.SyncVisible<CostPlanningServer.Model.Order>", null)
                        .WithMany("SyncUsers")
                        .HasForeignKey("SyncVisible<Order>Id");
                });
#pragma warning restore 612, 618
        }
    }
}
